### ISSUE TITLE
Install info?

### ISSUE THREAD

**Issue by peva3** [knoopx/plex-music-electron#1]
Hey, could I get some info on how to set this up? Thanks!

**Comment by knoopx** [comment]
If you just want to try it, you can find pre-built binaries for OSX in the releases tab. If you want to run/develop locally you need to clone the repo, install deps with `yarn` and run `yarn run development`. That will start electron with hot module reloading. To build it just execute `yarn run release`

**Comment by knoopx** [comment]
There's also an online version available at https://knoopx.github.io/plex-music/
